region              = "eu-west-1"
id_lookup_bucket    = "case-ids-lookup-123456"
zendesk_subdomain   = "your_subdomain"
zendesk_admin_email = "your_admin_email"
zendesk_token       = "your_api_key"
bearer_token        = "Bearer <your_token>"